version: '2'

services:
    worm-php:
        image: woohoolabs/php:3.2
        container_name: worm-php
        volumes:
            - .:/code
        command: /bin/bash -c "cd /code; php vendor/bin/phpunit"
