version: '2'

services:
    nginx:
        image: nginx:1.11-alpine
        container_name: worm-nginx
        networks:
            - worm
        volumes:
            - .:/code
        ports:
            - "$HOST_WEB_PORT:80"
        env_file:
            - .env
        command: /code/build/container/nginx/run.sh
        env_file:
            - .env
        depends_on:
            - php-fpm

      php-fpm:
        image: woohoolabs/php:3.1.4
        container_name: worm-php-fpm
        networks:
            - worm
        volumes:
            - .:/code
        env_file:
            - .env
        command: /code/build/container/php-fpm/run.sh
        depends_on:
            - mysql

    mysql:
        image: mysql:5.7
        container_name: worm-mysql
        ports:
            - "$HOST_MYSQL_PORT:3306"
        networks:
            - worm
        volumes:
            - mysql-data:/var/lib/mysql
        env_file:
            - .env

networks:
    worm:

volumes:
    mysql-data:
        driver: local
