version: '2'

services:
  worm-nginx:
    build:
      context: ./docker
      dockerfile: docker/nginx.dockerfile
    container_name: worm-nginx
    networks:
      - worm
    ports:
      - "$HOST_WEB_PORT:80"
    volumes:
      - .:/var/www
    env_file:
      - .env
    depends_on:
      - worm-php-fpm

  worm-php-fpm:
    build:
      context: ./docker
      dockerfile: docker/php.dockerfile
    container_name: worm-php-fpm
    networks:
      - worm
    volumes:
      - .:/var/www
    env_file:
      - .env

  worm-mysql:
    container_name: worm-mysql
    image: mysql:5.7
    ports:
      - "$HOST_MYSQL_PORT:3306"
    networks:
      - worm
    volumes:
      - mysql-data:/var/lib/mysql
    env_file:
      - .env

networks:
  worm:

volumes:
  mysql-data:
    driver: local
