version: '2'

services:
    worm-php:
        image: woohoolabs/php-fpm:7.4.0
        container_name: worm-php
        volumes:
            - .:/code
        command: /bin/sh -c "cd /code; php vendor/bin/phpunit"
